package main

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

type Tasks struct {
	name     string
	duration time.Duration
}

func main() {
	// Read input
	var startInfo string = "2024:10:1:13:45"
	var taskInfo string = "Research:1:Day,Prototyping:3:Day,Development:2:Week,Testing:5:Day,Deployment:1:Day,Maintenance:2:Day"
	// fmt.Scanln(&startInfo)
	// fmt.Scanln(&taskInfo)

	// Parse start time information
	startParts := strings.Split(startInfo, ":")
	year, _ := strconv.Atoi(startParts[0])
	month, _ := strconv.Atoi(startParts[1])
	day, _ := strconv.Atoi(startParts[2])
	hour, _ := strconv.Atoi(startParts[3])
	minute, _ := strconv.Atoi(startParts[4])

	// Create project start time
	startTime := time.Date(year, time.Month(month), day, hour, minute, 0, 0, time.UTC)

	// Parse task information
	taskEntries := strings.Split(taskInfo, ",")

	// TODO: Write your code below
	// - Process each task entry to extract name, duration value, and unit
	var tasks []Tasks

	for _, task := range taskEntries {
		taskParts := strings.Split(task, ":")
		name := taskParts[0]
		durationValue, _ := strconv.Atoi(taskParts[1])
		durationUnit := taskParts[2]

		var duration time.Duration

		switch durationUnit {
		case "Day":
			duration = time.Duration(durationValue) * 24 * time.Hour
		case "Week":
			duration = time.Duration(durationValue) * 7 * 24 * time.Hour
		case "Hour":
			duration = time.Duration(durationValue) * time.Hour
		}

		tasks = append(tasks, Tasks{
			name:     name,
			duration: duration,
		})
	}
	// - Create duration objects for each task
	fmt.Println("=== PROJECT DEADLINE CALCULATOR ===")
	fmt.Printf("Project start time: %s\n", startTime)
	// - Calculate task start and end times
	var (
		end           time.Time
		totalDuration time.Duration
		longestHours  time.Duration
		shortestHours time.Duration
		longestTask   string
		shortestTask  string
	)

	/// task loop
	for i, d := range tasks {
		totalDuration += d.duration

		if d.duration > longestHours {
			longestHours = d.duration
			longestTask = d.name
		}

		if i == 0 || d.duration < shortestHours {
			shortestHours = d.duration
			shortestTask = d.name
		}

		//transitions code
		end = startTime.Add(d.duration)

		fmt.Printf("Task: %s\n", d.name)
		fmt.Printf(" Duration: %v\n", d.duration)
		fmt.Printf(" Start: %v\n", startTime)
		fmt.Printf(" End: %s\n", end)

	}
	// - Find longest and shortest tasks
	fmt.Println("=== PROJECT TIMELINE ===")
	fmt.Printf("Project start: %v\n", startTime)
	fmt.Printf("Project end: %v\n", end)
	fmt.Printf("Total project duration: %v\n", totalDuration)
	// - Calculate project statistics
	fmt.Println("=== TASK ANALYSIS ===")
	fmt.Printf("Number of tasks: %d\n", len(taskEntries))
	fmt.Printf("Longest task: %s (%v)\n", longestTask, longestHours)
	fmt.Printf("Shortest task: %s (%v)\n", shortestTask, shortestHours)
	// - Display all required output sections

	fmt.Println("=== TASK TRANSITIONS ===")

	// transition
	currentTime := startTime
	var previousTaskName string
	var previousEndTime time.Time
	var transition time.Duration
	var totalWorkingDay float64
	var TotalWorkingHours float64
	projectStart := startTime
	current := projectStart

	for i, d := range tasks {

		//span

		current = current.Add(d.duration)

		totalWorkingDay += d.duration.Hours() / 24
		TotalWorkingHours += d.duration.Hours()

		taskEnd := currentTime.Add(d.duration)

		if i > 0 {
			transition = currentTime.Sub(previousEndTime)
			fmt.Printf("%s to %s: %v\n", previousTaskName, d.name, transition)

		}

		end = startTime.Add(d.duration)

		previousTaskName = d.name
		previousEndTime = currentTime.Add(d.duration)
		currentTime = taskEnd
	}

	projectEnd := current

	span := projectEnd.Sub(projectStart)

	calendarDays := int(span.Hours() / 24)

	// Output will be generated by your implementation above

	fmt.Println("=== PROJECT STATISTICS ===")
	fmt.Printf("Total working days: %v\n", totalWorkingDay)
	fmt.Printf("Total working hours: %v\n", TotalWorkingHours)
	fmt.Printf("Project spans %d calendar days\n", calendarDays)

	fmt.Println("Project timeline calculation completed successfully")
}
